name: Bert Proesmans
description: Presence on the internet is a must?
# Filename for image in header
avatar: BertFace.svg
# Links & Accounts
links:
  github: Bert-Proesmans

# Google Analytics web tracking code
# google_analytics: UA-112790006-1

# Your website URL (Used for Sitemap.xml and your RSS feed)
url: https://proesmans.eu
baseurl: ""
# Permalink for posts pages
paginate: 4
paginate_path: "/:num/"

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Sass partials directory (for @imports)
sass:
  style: :compressed # Default :expanded

plugins:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME